secs = input("Give me seconds to convert to minnutes, hours, and days")
secs = int(secs)
days = (secs//86400)
days1 = (secs % 86400)
hours = (days1//3600)
hours1 = (days1 % 3600)
minutes = (hours1//60)
minutes1 = (days1 % 60)
days = int(days)
hours = int(hours)
minutes = int(minutes)
print("You have this many days = " + str(days) + ", this many hours = " + str(hours)
      + ", this many minutes = " + str(minutes) + ", and this many seconds left = " + str(minutes1))
      
